GlobalWatchSystem/GlobalWatchSystem/Models/TransportPlan.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace GlobalWatchSystem.Models
{
    public class TransportPlan
    {
        [Key]
        [Index]
        public int Id { get; set; }

        [Index]
        [Required(ErrorMessageResourceType = typeof(Resources.Resources), ErrorMessageResourceName = "MsgFieldRequired")]
        [StringLength(50, MinimumLength = 3, ErrorMessageResourceType = typeof(Resources.Resources), ErrorMessageResourceName = "MsgFieldLength")]
        [Display(ResourceType = typeof(Resources.Resources), Name = "MenuPlanManagement")]
        public string Name { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm:ss}", ApplyFormatInEditMode = true, NullDisplayText="尚未开始")]
        [Display(ResourceType = typeof(Resources.Resources), Name = "StartTime")]
        public DateTime? startTime { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm:ss}", ApplyFormatInEditMode = true, NullDisplayText = "尚未结束")]
        [Display(ResourceType = typeof(Resources.Resources), Name = "EndTime")]
        public DateTime? stopTime { get; set; }

        [Display(ResourceType = typeof(Resources.Resources), Name = "Description")]
        public string Remark { get; set; }
    }
}

GlobalWatchSystem/GlobalWatchSystem/Controllers/TransportPlanController.cs
using GlobalWatchSystem.Data.Repository;
using GlobalWatchSystem.Helpers;
using GlobalWatchSystem.Models;
using GlobalWatchSystem.Models.ViewModel;
using Newtonsoft.Json;
using NLog;
using SharpRepository.Repository.Queries;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;


namespace GlobalWatchSystem.Controllers
{
    public class TransportPlanController : BaseController
    {
        private readonly ITransportPlanRepository transportPlanRepository;
        private readonly IAreaRepository areaRepository;
        private readonly IAuditLogRepository auditLogRepository;
        private readonly IDevicePlanRecordRepository devicePlanRepository;
        private readonly IDtuGpsRepository dtuGpsRepository;
        private readonly IDeviceRepository deviceRepository;

        private readonly Logger logger = LogManager.GetCurrentClassLogger();

        public TransportPlanController(ITransportPlanRepository transportPlanRepository, 
            IAreaRepository areaRepository, 
            IAuditLogRepository auditLogRepository, 
            IDevicePlanRecordRepository devicePlanRepository,
            IDtuGpsRepository dtuGpsRepository,
            IDeviceRepository deviceRepository)
            : base(areaRepository)
        {
            this.transportPlanRepository = transportPlanRepository;
            this.areaRepository = areaRepository;
            this.auditLogRepository = auditLogRepository;
            this.devicePlanRepository = devicePlanRepository;
            this.dtuGpsRepository = dtuGpsRepository;
            this.deviceRepository = deviceRepository;
        }

        public ActionResult Index(int page = 1)
        {
            ViewBag.Pagination = new Pagination { TotalCount = transportPlanRepository.Count(), CurrentPage = page };
            List<int> areaIds = CurrentAvailableAreas.Select(area => area.Id).ToList();
            IEnumerable<TransportPlan> plans = transportPlanRepository.GetAll(new PagingOptions<TransportPlan>(page, Pagination.DefaultPageSize, "Name"));

            return View(plans);
        }


        [HttpPost]
        public ActionResult Delete(int id)
        {
            var exising = transportPlanRepository.Get(id);
            if(exising == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            transportPlanRepository.Delete(exising);

            auditLogRepository.Add(AuditLogBuilder.Builder()
                .User(HttpContext.User.Identity.Name)
                .Deleted(typeof(TransportPlan), exising.Name)
                .With(new ChangeInfo().AddChange(() => exising.Name).ToJson())
                .Build());

            logger.Info("User '{0}' deleted TransportPlan '{1}'.", Identity.Name, exising.Name);

            return RedirectToAction("Index");
        }

        public ActionResult ViewPlan(int id)
        {
            var plan = transportPlanRepository.Get(id);

            if(plan == null)
            {
                return HttpNotFound();
            }
            //首先查询到计划关联的所有的设备
            var records = devicePlanRepository.FindAll(p => p.PlanId == id);
            //if(plan.stopTime != null)
            //{
            //    records = records.Where(p => { if (p.endTime == null) { return true; } else return p.endTime <= plan.stopTime; });
            //}

            var devIds = records.Select(p=>p.DeviceId);

            var imeis = deviceRepository.FindAll(p=>devIds.Contains(p.Id)).Select(d=>d.IMEI);

            List<TransportTrack> tracks = new List<TransportTrack>();

            DateTime endTime = plan.stopTime == null ? DateTime.Now : plan.stopTime.Value;

            foreach(var ele in records)
            {
                DateTime devEndTime = ele.endTime == null ? DateTime.Now : ele.endTime.Value;

                DateTime realEndTime = devEndTime > endTime ? endTime : devEndTime;

                var query = dtuGpsRepository.FindAll(d => imeis.Contains(d.IMEI) && d.RecvTime >= ele.startTime && d.RecvTime < realEndTime, new SortingOptions<DtuGPS>("RecvTime"));

                Device device = deviceRepository.Get(ele.DeviceId.Value);
                var eles = query.Select(gps => new TransportTrack
                {
                    name = device != null ? device.Name : "",
                    latitude = gps.Latitude,
                    longitude = gps.Longitude
                });
                tracks.AddRange(eles);
            }
            ViewBag.PlanName = plan.Name;
            ViewBag.Data = JsonConvert.SerializeObject(tracks);
            return View();
        }

        public ActionResult StartPlan(int id)
        {
            var plan = transportPlanRepository.Get(id);

            if (plan == null)
            {
                return HttpNotFound();
            }
            plan.startTime = DateTime.Now;

            transportPlanRepository.Update(plan);

            return RedirectToAction("Index");
        }

        public ActionResult StopPlan(int id)
        {
            var plan = transportPlanRepository.Get(id);

            if (plan == null)
            {
                return HttpNotFound();
            }
            plan.stopTime = DateTime.Now;

            transportPlanRepository.Update(plan);

            return RedirectToAction("Index");
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Edit(int id)
        {
           
            var plan = transportPlanRepository.Get(id);

            if(plan == null)
            {
                return HttpNotFound();
            }

            return View(plan);
        }
        [HttpPost]
        public ActionResult Edit(TransportPlan model)
        {
            if(!ModelState.IsValid)
            {
                View(model); 
            }


            var existing = transportPlanRepository.Get(model.Id);
            existing.Name = model.Name;
            existing.startTime = model.startTime;
            existing.stopTime = model.stopTime;
            existing.Remark = model.Remark;

            transportPlanRepository.Update(existing);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Create(TransportPlan model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            transportPlanRepository.Add(model);

         
            auditLogRepository.Add(AuditLogBuilder.Builder()
                .User(HttpContext.User.Identity.Name)
                .Added(typeof(TransportPlan), model.Name)
                .With(new ChangeInfo().AddChange(() => model.Name).ToJson())
                .Build());

            logger.Info("User '{0}' created TransportPlan '{1}'.", Identity.Name, model.Name);

            return RedirectToAction("Index");
        }
    }
}

GlobalWatchSystem/GlobalWatchSystem/Views/TransportPlan/Create.cshtml
@model GlobalWatchSystem.Models.TransportPlan

<hgroup class="col-lg-12">
    <h3 class="page-header">@Resources.MenuPlanManagement</h3>
</hgroup>

<article>
    @using (Html.BeginForm("Create", "TransportPlan"))
    {
        @Html.AntiForgeryToken()

        <div class="col-lg-6">
            <div class="form-group">
                <div class="edit-item">
                    @Html.LabelFor(m => m.Name)
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(u => u.Name)
                </div>

                <div class="edit-item">
                    @Html.LabelFor(m => m.startTime)
                    @Html.TextBoxFor(m => m.startTime,  new { @class = "form-control"})
                    @Html.ValidationMessageFor(m => m.startTime)
                </div>
                <div class="edit-item">
                    @Html.LabelFor(m => m.stopTime)
                    @Html.TextBoxFor(m => m.stopTime, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.stopTime)
                </div>
                <div class="edit-item">
                    @Html.LabelFor(m => m.Remark)
                    @Html.TextAreaFor(m => m.Remark, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Remark)
                </div> 
            </div>
            <button type="submit" class="btn btn-default">@Resources.ActionSave</button>
        </div>
    }
</article>

GlobalWatchSystem/GlobalWatchSystem/Views/TransportPlan/Edit.cshtml
@model GlobalWatchSystem.Models.TransportPlan

<hgroup class="col-lg-12">
    <h3 class="page-header">@Resources.MenuPlanManagement</h3>
</hgroup>

<article>
    @using (Html.BeginForm("Edit", "TransportPlan"))
    {
        @Html.AntiForgeryToken()

        <div class="col-lg-6">
            <div class="form-group">
                <div class="edit-item">
                    @Html.LabelFor(m => m.Name)
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(u => u.Name)
                </div>

                <div class="edit-item">
                    @Html.LabelFor(m => m.startTime)
                    @Html.TextBoxFor(m => m.startTime, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.startTime)
                </div>
                <div class="edit-item">
                    @Html.LabelFor(m => m.stopTime)
                    @Html.TextBoxFor(m => m.stopTime, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.stopTime)
                </div>
                <div class="edit-item">
                    @Html.LabelFor(m => m.Remark)
                    @Html.TextAreaFor(m => m.Remark, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Remark)
                </div>
            </div>
            <button type="submit" class="btn btn-default">@Resources.ActionSave</button>
        </div>
    }
</article>

GlobalWatchSystem/GlobalWatchSystem/Views/TransportPlan/Index.cshtml
@using System
@using GlobalWatchSystem.Helpers
@using GlobalWatchSystem.Models.ViewModel
@model System.Collections.Generic.IEnumerable<GlobalWatchSystem.Models.TransportPlan>

<hgroup>
    <h3 class="page-header">@Resources.MenuPlanManagement</h3>
</hgroup>

<article>
    <div class="table-responsive">
        @Html.ValidationSummary(true)
        <table class="table table-bordered table-hover table-striped">
            <thead>
                <tr>
                    <th>@Resources.MenuPlanManagement</th>
                    <th>@Resources.StartTime</th>
                    <th>@Resources.EndTime</th>
                    <th>@Resources.Description</th>
                    <th>@Resources.Actions</th>
                    <th>@Resources.DeviceData</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var area in Model)
                {
                    <tr>
                        <td>@area.Name</td>
                        <td>@area.startTime</td>
                        <td>@area.stopTime</td>
                        <td>@area.Remark</td>
                        <td>
                            @if(area.startTime == null)
                            { 
                                <a href="@Url.Action("StartPlan", "TransportPlan", new {id = area.Id})">
                                    <button type="button" class="btn btn-xs btn-default">@Resources.StartPlan</button>
                                </a>
                            }
                            @if(area.stopTime == null)
                            {
                                <a href="@Url.Action("StopPlan", "TransportPlan", new {id = area.Id})">
                                    <button type="button" class="btn btn-xs btn-default">@Resources.StopPlan</button>
                                </a>
                            }
                            <a href="@Url.Action("Edit", "TransportPlan", new {id = area.Id})">
                                <button type="button" class="btn btn-xs btn-default">@Resources.ActionEdit</button>
                            </a>
                            @using (Html.BeginForm("delete", "TransportPlan", new { id = area.Id }, FormMethod.Post, new { @style = "display:inline" }))
                            {
                                <input type="submit" class="btn btn-xs btn-default"
                                       data-delete-alert="@String.Format(Resources.MsgDeleteAlert, area.Name)"
                                       data-confirm="@Resources.LabelConfirm"
                                       data-cancel="@Resources.LabelCancel"
                                       value="@Resources.ActionDelete" />
                            }
                        </td>
                        <td>
                            <a href="@Url.Action("ViewPlan", "TransportPlan", new {id = area.Id})">
                                <button type="button" class="btn btn-xs btn-default">@Resources.ViewPlanTrace</button>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="pull-right">@Html.Pagination((Pagination)ViewBag.Pagination, "area")</div>
    @Html.ActionLink(@Resources.ActionCreatePlan, "create", "TransportPlan")

</article>

GlobalWatchSystem/GlobalWatchSystem/Views/TransportPlan/ViewPlan.cshtml
<hgroup>
    <h3 class="page-header">@Resources.ViewPlanTrace - @ViewBag.PlanName</h3>
</hgroup>
<link href="~/assets/css/map.css" rel="stylesheet" />
<article>
    <div id="mapContainer" style="width:auto;height:768px"
         data-dev-gpsdata="@ViewBag.Data" data-dev-startpoint="@Resources.StartPoint">
    </div>

</article>
@section MapTrackScripts{
    <script src="http://webapi.amap.com/maps?v=1.3&key=20bfaeaa29dde4edc6b521bdb13252f0"></script>
    <script src="http://api.map.baidu.com/api?v=2.0&ak=j8HK07y0Sc6V3n9UMLo1Wd5IYFCBMEyU"></script>
    <script src="~/assets/js/MapTrackBaidu.js"></script>
}