GlobalWatchSystem/GlobalWatchSystem/Models/Device.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Newtonsoft.Json;
using System.ComponentModel;

namespace GlobalWatchSystem.Models
{
    public class Device
    {
        [Index]
        public int Id { get; set; }

        [Display(ResourceType = typeof (Resources.Resources), Name = "DeviceName")]
        public string Name { get; set; }

        [Display(ResourceType = typeof (Resources.Resources), Name = "Description")]
        public string Description { get; set; }

        [Display(ResourceType = typeof (Resources.Resources), Name = "DeviceIMEI")]
        public string IMEI { get; set; }

        public float Battery { get; set; }
        public PowerMode PowerMode { get; set; }
        public String Data { get; set; }
        public DateTime? DataDttm { get; set; }

        [Display(ResourceType = typeof (Resources.Resources), Name = "DeviceNumber")]
        public string SimNumber { get; set; }

        [Display(ResourceType = typeof (Resources.Resources), Name = "AreaBelonged")]
        public int AreaId { get; set; }

        [Display(ResourceType = typeof(Resources.Resources), Name = "MenuPlanManagement")]
        [ForeignKey("TransportPlan")]
        public Int32? TransportPlanId { get; set; }

        public virtual TransportPlan TransportPlan { get; set; }

        [ForeignKey("DeviceMeta")]
        public Int32? DeviceMetaId { get; set; }

        public virtual DeviceMeta DeviceMeta { get; set; }

        public List<DataEntry> GetData()
        {
            if (String.IsNullOrEmpty(Data)) return new List<DataEntry>();
            return JsonConvert.DeserializeObject<List<DataEntry>>(Data);
        }
    }

    public enum PowerMode
    {
        Battary = 0,
        Power = 1
    }

    public class DataEntry
    {
        public int Channel { get; set; }
        public int Type { get; set; }
        public float Value { get; set; }
    }
}

GlobalWatchSystem/GlobalWatchSystem/Controllers/DeviceController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using GlobalWatchSystem.Data.Repository;
using GlobalWatchSystem.Helpers;
using GlobalWatchSystem.Models;
using GlobalWatchSystem.Models.ViewModel;
using NLog;
using SharpRepository.Repository.Queries;
using System;
using System.IO;
using WebGrease.Css.Extensions;
using GlobalWatchSystem.Data;

namespace GlobalWatchSystem.Controllers
{
    public class DeviceController : BaseController
    {
        private readonly IAreaRepository areaRepository;
        private readonly IAuditLogRepository auditLogRepository;
        private readonly IDeviceRepository deviceRepository;
        private readonly IDtuDataRepository dtuDataRepository;
        private readonly IDtuGpsRepository dtuGpsRepository;
        private readonly ITransportPlanRepository transportPlanRepository;
        private readonly IDevicePlanRecordRepository devicePlanRepository;
        private readonly IDeviceMetaRepository deviceMetaRepository;
        private readonly IDeviceUnitRepository deviceUnitRepository;

        private readonly Logger logger = LogManager.GetCurrentClassLogger();

        public DeviceController(IAreaRepository areaRepository, IDeviceRepository deviceRepository,
            IDtuDataRepository dtuDataRepository,
            IAuditLogRepository auditLogRepository,
            IDtuGpsRepository dtuGpsRepository,
            ITransportPlanRepository transportPlanRepository,
            IDevicePlanRecordRepository devicePlanRepository,
            IDeviceMetaRepository deviceMetaRepository,
            IDeviceUnitRepository deviceUnitRepository)
            : base(areaRepository)
        {
            this.areaRepository = areaRepository;
            this.deviceRepository = deviceRepository;
            this.dtuDataRepository = dtuDataRepository;
            this.auditLogRepository = auditLogRepository;
            this.dtuGpsRepository = dtuGpsRepository;
            this.transportPlanRepository = transportPlanRepository;
            this.devicePlanRepository = devicePlanRepository;
            this.deviceMetaRepository = deviceMetaRepository;
            this.deviceUnitRepository = deviceUnitRepository;
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            Device exising = deviceRepository.Get(id);
            deviceRepository.Delete(exising);

            auditLogRepository.Add(AuditLogBuilder.Builder()
                .User(HttpContext.User.Identity.Name)
                .Deleted(typeof(Device), exising.Name)
                .With(new ChangeInfo().AddChange(() => exising.Name).ToJson())
                .Build());

            logger.Info("User '{0}' deleted device '{1}'.", Identity.Name, exising.Name);

            return RedirectToAction("TableMode");
        }

        [HttpGet]
        public ActionResult Export(int from, int to, string deviceImei)
        {
            DateTime start = UnixTimeStampToDateTime(from);
            DateTime end = UnixTimeStampToDateTime(to);

            var tempFileName = Path.GetTempFileName();
            var fileInfo = new FileInfo(tempFileName);
            fileInfo.Attributes = FileAttributes.Temporary;
            using (var writer = System.IO.File.AppendText(tempFileName))
            {
                writer.WriteLine("IMEI,RecvDttm,Channel,Unit,Value");
                var dtuDatas = dtuDataRepository.FindAll(data => data.IMEI == deviceImei && data.RecvTime >= start && data.RecvTime <= end).OrderBy(data => data.RecvTime);
                dtuDatas.ForEach(record =>
                    writer.WriteLine("{0},{1},{2},{3},{4}", record.IMEI, record.RecvTime, record.Channel, record.DataType, record.Value));
            }
            return File(System.IO.File.ReadAllBytes(tempFileName), "text/csv", String.Format("{0}.csv", deviceImei));
        }

        public static DateTime UnixTimeStampToDateTime(int unixTimeStamp)
        {
            // Unix timestamp is seconds past epoch
            System.DateTime dtDateTime = new DateTime(1970, 1, 1, 0, 0, 0, 0, System.DateTimeKind.Utc);
            dtDateTime = dtDateTime.AddSeconds(unixTimeStamp).ToLocalTime();
            return dtDateTime;
        }


        public ActionResult Edit(int id)
        {
            Device existing = deviceRepository.Get(id);
            if (existing == null)
            {
                return RedirectToAction("TableMode");
            }

            var model = new DeviceModel
            {
                Id = existing.Id,
                Name = existing.Name,
                Description = existing.Description,
                IMEI = existing.IMEI,
                SimNumber = existing.SimNumber,
                AreaId = existing.AreaId,
                TransportPlanId = existing.TransportPlanId
            };

            var sortingOptions = new SortingOptions<DtuGPS, DateTime>(x => x.RecvTime, true);
            DtuGPS gps = dtuGpsRepository.FindAll(g => g.IMEI == existing.IMEI, sortingOptions).FirstOrDefault();
            if (gps != null)
            {
                model.longitude = gps.Longitude;
                model.latitude = gps.Latitude;
            }

            ViewBag.Areas = GetAreaSelectItems();
            ViewBag.Plans = GetPlanSelectItems();
            ViewBag.DeviceTypes = GetDeviceTypeItems();
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(DeviceModel model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Areas = GetAreaSelectItems();
                ViewBag.Plans = GetPlanSelectItems();
                ViewBag.DeviceTypes = GetDeviceTypeItems();
                return View(model);
            }

            Device existing = deviceRepository.Get(model.Id);

            if (existing.TransportPlanId != model.TransportPlanId)
            {
                var ele = devicePlanRepository.Find(p => p.DeviceId == existing.Id && p.PlanId == existing.TransportPlanId, new SortingOptions<DevicePlanRecord>("startTime", true));
                if (ele != null)
                {
                    ele.endTime = DateTime.Now;
                    devicePlanRepository.Update(ele);
                }
                if (model.TransportPlanId != null)
                {
                    devicePlanRepository.Add(new DevicePlanRecord { DeviceId = model.Id, PlanId = model.TransportPlanId, startTime = DateTime.Now });
                }
            }

            UpdateDeviceFromModel(existing, model);
            deviceRepository.Update(existing);

            dtuGpsRepository.Add(new DtuGPS
            {
                IMEI = model.IMEI,
                RecvTime = DateTime.Now,
                Longitude = model.longitude,
                Latitude = model.latitude
            });

            AuditDeviceChange(existing);


            return RedirectToAction("TableMode");
        }

        private void AuditDeviceChange(Device existing)
        {
            string changes = new ChangeInfo()
                .AddChange(() => existing.Name)
                .AddChange(() => existing.Description)
                .AddChange(() => existing.SimNumber)
                .AddChange(() => existing.IMEI)
                .AddChange(() => existing.AreaId)
                .AddChange(()=>existing.DeviceMetaId)
                .ToJson();
            auditLogRepository.Add(AuditLogBuilder.Builder()
                .User(HttpContext.User.Identity.Name)
                .Updated(typeof(Device), existing.Name)
                .With(changes)
                .Build());
        }

        public ActionResult Create()
        {
            ViewBag.Areas = GetAreaSelectItems();
            ViewBag.Plans = GetPlanSelectItems();
            ViewBag.DeviceTypes = GetDeviceTypeItems();
            return View();
        }

        [HttpPost]
        public ActionResult Create(DeviceModel deviceModel)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Areas = GetAreaSelectItems();
                ViewBag.Plans = GetPlanSelectItems();
                ViewBag.DeviceTypes = GetDeviceTypeItems();
                return View(deviceModel);
            }

            var device = new Device();
            UpdateDeviceFromModel(device, deviceModel);
            deviceRepository.Add(device);

            if (device.TransportPlanId != null)
            {
                devicePlanRepository.Add(new DevicePlanRecord { DeviceId = device.Id, PlanId = device.TransportPlanId, startTime = DateTime.Now });
            }

            dtuGpsRepository.Add(new DtuGPS
            {
                IMEI = deviceModel.IMEI,
                RecvTime = DateTime.Now,
                Longitude = deviceModel.longitude,
                Latitude = deviceModel.latitude
            });

            auditLogRepository.Add(AuditLogBuilder.Builder()
                .User(HttpContext.User.Identity.Name)
                .Added(typeof(Device), device.Name)
                .With(new ChangeInfo().AddChange(() => device.Name).ToJson())
                .Build());

            logger.Info("User '{0}' created device '{1}'.", Identity.Name, device.Name);

            return RedirectToAction("TableMode");
        }

        public ActionResult Tempmode12chs(int page = 1)
        {
            string deviceType = "12路温度仪";

            ViewBag.Pagination = new Pagination { TotalCount = deviceRepository.Count(), CurrentPage = page };
            List<int> areaIds = CurrentAvailableAreas.Select(area => area.Id).ToList();
            IEnumerable<DeviceModel> devices = deviceRepository.
                FindAll(device => areaIds.Contains(device.AreaId) && (device.DeviceMeta == null ? true : device.DeviceMeta.DeviceType == deviceType),
                    new PagingOptions<Device>(page, Pagination.DefaultPageSize, "Name"))
                .Select(device =>
                    new DeviceModel
                    {

GlobalWatchSystem/GlobalWatchSystem/Views/Device/Create.cshtml
@model GlobalWatchSystem.Models.ViewModel.DeviceModel

<hgroup class="col-lg-12">
<h3 class="page-header">@Resources.DeviceManagementCreate</h3>
</hgroup>

<script>
    var btnTitle = '@Resources.btnOkTip';
    var winTitle = '@Resources.FetchGPSFromMap';
    var obj = window;
    obj.btnTitle = btnTitle;
    function LocateGPSFromMap(math)
    {
        window.open(math, winTitle, 'height=550,width=600,top=300,left=300,toolbar=no,menubar=no,scrollbars=no, resizable=yes,location=no, status=no');
    }
</script>
<article>
    @using (Html.BeginForm("create", "device"))
    {
        @Html.AntiForgeryToken()

        <div class="col-lg-6">
            <div class="form-group">
                <div class="edit-item">
                    @Html.LabelFor(m => m.Name)
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(u => u.Name)
                </div>

                <div class="edit-item">
                    @Html.LabelFor(m => m.Description)
                    @Html.TextAreaFor(m => m.Description, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Description)
                </div>
                <div class="edit-item">
                    @Html.LabelFor(m => m.IMEI)
                    @Html.TextBoxFor(m => m.IMEI, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.IMEI)
                </div>
                <div class="edit-item">
                    @Html.LabelFor(m => m.SimNumber)
                    @Html.TextBoxFor(m => m.SimNumber, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.SimNumber)
                </div>
                <div class="edit-item">
                    @Html.LabelFor(u => u.AreaId)
                    @Html.DropDownList("AreaId", (IEnumerable<SelectListItem>)ViewBag.Areas, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.AreaId)
                </div>
                <div class="edit-item" data-tip-val="@Resources.ChangePlanTip" id="tranportItem">
                    @Html.LabelFor(u => u.TransportPlanId)
                    @Html.DropDownList("TransportPlanId", (IEnumerable<SelectListItem>)ViewBag.Plans, new { @class = "form-control", @id = "transportPlan" })
                    @Html.ValidationMessageFor(m => m.TransportPlan)
                </div>
                <div class="edit-item" data-tip-val="@Resources.DeviceType" id="deviceMetaItem">
                    @Html.LabelFor(u => u.DeviceMetaId)
                    @Html.DropDownList("DeviceMetaId", (IEnumerable<SelectListItem>)ViewBag.DeviceTypes, new { @class = "form-control", @id = "deviceMeta" })
                    @Html.ValidationMessageFor(m => m.DeviceMetaId)
                </div>
                <div class="edit-item">
                    @Html.LabelFor(u => u.longitude)
                    @Html.TextBoxFor(m => m.longitude, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.longitude)
                </div>
                <div class="edit-item">
                    @Html.LabelFor(u => u.latitude)
                    @Html.TextBoxFor(m => m.latitude, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.latitude)
                </div>
                <button type="button" class="btn btn-default" onclick="LocateGPSFromMap('../GetGPSFromMap.html')">@Resources.FetchGPSFromMap</button>
             </div>
            
            <button type="submit" class="btn btn-default">@Resources.ActionSave</button>
        </div>
    }
</article>

GlobalWatchSystem/GlobalWatchSystem/Views/Device/CurveMode.cshtml
@model GlobalWatchSystem.Models.ViewModel.DeviceModel

<hgroup>
    <h3 class="page-header">@Resources.MenuDeviceManagement - @Resources.devCurveMode</h3>
</hgroup>

<article>
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/assets/css/sb-admin.css" rel="stylesheet" />
    <link href="~/assets/css/plugins/morris.css" rel="stylesheet" />
    <link href="~/assets/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row">
                <span style="display:none" id="deviceId">@Model.Id</span>
                <span style="display:none" id ="devIMEI" data-channel-desc="@Resources.ChannelNo">@Model.IMEI</span>
                <div class="col-md-12 device-realtime-data">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            
                            <h3 class="panel-title">@Resources.DeviceInformation - @Html.DisplayFor(m => m.Name) <div class="pull-right">@Resources.LastUpdate: <span class="last-update" style="color:#ffffff">-</span></div></h3>
                        </div>
                        <div class="panel-body">
                            <div class="col-lg-2 text-center temperature">
                                <div class="big-number">
                                    -
                                </div>
                                <div>
                                    @Resources.Temperature 1
                                </div>
                            </div>
                            <div class="col-lg-2 text-center humidity">
                                <div class="big-number">
                                    -
                                </div>
                                <div>
                                    @Resources.Humidity 1
                                </div>
                            </div>
                            <div class="col-lg-2 text-center temperature">
                                <div class="big-number">
                                    -
                                </div>
                                <div>
                                    @Resources.Temperature 2
                                </div>
                            </div>
                            <div class="col-lg-2 text-center humidity">
                                <div class="big-number">
                                    -
                                </div>
                                <div>
                                    @Resources.Humidity 2
                                </div>
                            </div>
                            <div class="col-lg-4 text-center power">
                                <div class="big-number">
                                    -
                                </div>
                                <div>
                                    @Resources.Power
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <h3 class="panel-title"><i class="fa fa-long-arrow-right"></i>@Resources.chartTemperature - @Html.DisplayFor(m => m.Name)</h3>
                        </div>
                        <div class="panel-body">
                            <div id="temp-line-chart"></div>
                            <div class="text-right">
                                <a href="#">@Resources.chartViewDetails <i class="fa fa-arrow-circle-right"></i></a>
                            </div>
                        </div>
                    </div> 
                </div>
            </div>
        </div>
    </div>
</article>
@section CurveModeScripts{
    <!-- Morris Charts JavaScript -->
    <script src="~/assets/js/plugins/morris/raphael.min.js"></script>
    <script src="~/assets/js/plugins/morris/morris.min.js"></script>
    <script src="~/assets/js/chartlibrary.js"></script>
}

GlobalWatchSystem/GlobalWatchSystem/Views/Device/Edit.cshtml
@model GlobalWatchSystem.Models.ViewModel.DeviceModel


<hgroup class="col-lg-12">
    <h3 class="page-header">@Resources.DeviceManagementEdit</h3>
</hgroup>
<script>
    var btnTitle = '@Resources.btnOkTip';
    var winTitle = '@Resources.FetchGPSFromMap';
    var obj = window;
    obj.btnTitle = btnTitle;
    function LocateGPSFromMap(math)
    {
        window.open(math, winTitle, 'height=550,width=600,top=300,left=300,toolbar=no,menubar=no,scrollbars=no, resizable=yes,location=no, status=no');
    }
</script>
<article>
    @using (Html.BeginForm("edit", "device"))
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(m => m.Id)
        
        <div class="col-lg-6">
            <div class="form-group">
                <div class="edit-item">
                    @Html.LabelFor(m => m.Name)
                    @Html.TextBoxFor(m => m.Name, new {@class = "form-control", @readonly = "true"})
                </div>

                <div class="edit-item">
                    @Html.LabelFor(m => m.Description)
                    @Html.TextAreaFor(m => m.Description, new {@class = "form-control"})
                    @Html.ValidationMessageFor(m => m.Description)
                </div>
                <div class="edit-item">
                    @Html.LabelFor(m => m.IMEI)
                    @Html.TextBoxFor(m => m.IMEI, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.IMEI)
                </div>
                <div class="edit-item">
                    @Html.LabelFor(m => m.SimNumber)
                    @Html.TextBoxFor(m => m.SimNumber, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.SimNumber)
                </div>
                <div class="edit-item">
                    @Html.LabelFor(u => u.AreaId)
                    @Html.DropDownList("AreaId", (IEnumerable<SelectListItem>) ViewBag.Areas, new {@class = "form-control"})
                    @Html.ValidationMessageFor(m => m.AreaId)
                </div>
                <div class="edit-item" data-tip-val="@Resources.ChangePlanTip" id="tranportItem">
                    @Html.LabelFor(u => u.TransportPlanId)
                    @Html.DropDownList("TransportPlanId", (IEnumerable<SelectListItem>)ViewBag.Plans, new { @class = "form-control", @id = "transportPlan" })
                    @Html.ValidationMessageFor(m => m.TransportPlan)
                </div>
                <div class="edit-item" data-tip-val="@Resources.DeviceType" id="deviceMetaItem">
                    @Html.LabelFor(u => u.DeviceMetaId)
                    @Html.DropDownList("DeviceMetaId", (IEnumerable<SelectListItem>)ViewBag.DeviceTypes, new { @class = "form-control", @id = "deviceMeta" })
                    @Html.ValidationMessageFor(m => m.DeviceMetaId)
                </div>
                <div class="edit-item">
                    @Html.LabelFor(u => u.longitude)
                    @Html.TextBoxFor(m => m.longitude, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.longitude)
                </div>
                <div class="edit-item">
                    @Html.LabelFor(u => u.latitude)
                    @Html.TextBoxFor(m => m.latitude, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.latitude)
                </div>
                <button type="button" class="btn btn-default" onclick="LocateGPSFromMap('../../GetGPSFromMap.html')">@Resources.FetchGPSFromMap</button>
            </div>
            <button type="submit" class="btn btn-default">@Resources.ActionSave</button>
        </div>
    }
</article>

@section TableEditJS{
    <script src="~/assets/js/tableEdit.js"></script>
}

GlobalWatchSystem/GlobalWatchSystem/Views/Device/HistoryMode.cshtml
@model GlobalWatchSystem.Models.ViewModel.DeviceModel

<hgroup>
    <h3 class="page-header">@Resources.MenuDeviceManagement - @Resources.devHistoryMode</h3>
</hgroup>
<article id="device-history">
    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-8">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h3 class="panel-title">@Resources.DeviceInformation</h3>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-4">
                                    <span class="head">@Resources.DeviceName : </span> @Html.DisplayFor(m => m.Name)
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-4">
                                    <span class="head">@Resources.DeviceIMEI : </span>
                                    <label id="devIMEI" data-channel-desc="@Resources.ChannelNo">@Html.DisplayFor(m => m.IMEI)</label>
                                </div>
                                <div class="col-lg-4">
                                    <span class="head">@Resources.DeviceNumber : </span> @Html.DisplayFor(m => m.SimNumber)
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-4">
                                    <span class="head">@Resources.StartTime : </span>
                                    <input size="16" type="text" value="@DateTime.Now.AddHours(-1).ToString("yyyy-MM-dd HH:mm")" id="startTimePicker" readonly class="form_datetime">
                                </div>
                                <div class="col-lg-4">
                                    <span class="head">@Resources.EndTime : </span>
                                    <input size="16" type="text" value="@DateTime.Now.ToString("yyyy-MM-dd HH:mm")" id="endTimePicker" readonly class="form_datetime">
                                </div>
                                <div class="col-lg-4">
                                    <button type="button" class="btn btn-default" id="btnView">@Resources.Query</button>
                                    <button type="button" class="btn btn-default" id="btnExport">@Resources.ExportData</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <h3 class="panel-title"><i class="fa fa-long-arrow-right"></i>@Resources.chartTemperature</h3>
                        </div>
                        <div class="panel-body">
                            <div id="temp-line-chart"></div>
                            <div class="text-right">
                                <a href="#">@Resources.chartViewDetails <i class="fa fa-arrow-circle-right"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</article>
@section HistoryModeScripts{
    <script src="~/assets/js/bootstrap-datetimepicker.min.js"></script>
    <script src="~/assets/js/locales/bootstrap-datetimepicker.zh-cn.js"></script>
    <script src="~/assets/js/plugins/morris/raphael.min.js"></script>
    <script src="~/assets/js/plugins/morris/morris.min.js"></script>
    <script src="~/assets/js/historychartlibrary.js"></script>
}

GlobalWatchSystem/GlobalWatchSystem/Views/Device/Index.cshtml
@using System
@using GlobalWatchSystem.Helpers
@using GlobalWatchSystem.Models.ViewModel
@model System.Collections.Generic.IEnumerable<GlobalWatchSystem.Models.ViewModel.DeviceModel>

<hgroup>
    <h3 class="page-header">@Resources.MenuDeviceManagement - @Resources.devListView</h3>
</hgroup>

<article>
    <div class="table-responsive">
        <table class="table table-bordered table-hover table-striped">
            <thead>
                <tr>
                    <th>@Resources.DeviceName</th>
                    <th>@Resources.AreaBelonged</th>
                    <th>@Resources.DeviceIMEI</th>
                    <th>@Resources.DeviceNumber</th>
                    <th>@Resources.Description</th>
                    <th>@Resources.Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (DeviceModel device in Model)
                {
                    <tr>
                        <td>@device.Name</td>
                        <td>@device.AreaName</td>
                        <td>@device.IMEI</td>
                        <td>@device.SimNumber</td>
                        <td>@device.Description</td>
                        <td>
                            <a href="@Url.Action("edit", "device", new {id = device.Id})">
                                <button type="button" class="btn btn-xs btn-default">@Resources.ActionEdit</button>
                            </a>
                            @using (Html.BeginForm("delete", "device", new { id = device.Id }, FormMethod.Post, new { @style = "display:inline" }))
                            {
                                <input type="submit" class="btn btn-xs btn-default"
                                       data-delete-alert="@String.Format(Resources.MsgDeleteAlert, device.Name)"
                                       data-confirm="@Resources.LabelConfirm"
                                       data-cancel="@Resources.LabelCancel"
                                       value="@Resources.ActionDelete" />
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    @Html.ActionLink(@Resources.ActionCreateDevice, "create", "device")
    <div class="pull-right">@Html.Pagination((Pagination)ViewBag.Pagination, "device")</div>
</article>

GlobalWatchSystem/GlobalWatchSystem/Views/Device/MapMode.cshtml
    
<hgroup>
    <h3 class="page-header">@Resources.MenuDeviceManagement - @Resources.devMapView</h3>
</hgroup>
<link href="~/assets/css/map.css" rel="stylesheet" />
<article  > 
    <div id="tip" class="invisible">
        <label hidden="hidden" id="areaId">@ViewBag.areaId</label>
        <input type="button" value="添加点标记覆盖物" onclick="displayMarker()"  />
        <input type="button" value="删除点" onclick="delMarker()" />
        <input type="button" value="隐藏点" onclick="showMarkerByTitle('marker 1',false)" />
        <input type="button" value="打开点1信息窗" onclick="addInfoWindow(findMarkerByTitle('marker 1'))" />
        <input type="button" value="绘制曲线" onclick="addLine()" />
        <a href="@Url.Action("CurveMode","Device")">查看曲线</a>
    </div>
    <div id="mapContainer" style="width:auto;height:768px" data-dev-infors="@Resources.DeviceInformation"
         data-dev-name="@Resources.DeviceName"
         data-dev-belongto="@Resources.AreaBelonged"
         data-dev-curve="@Resources.devCurveMode"
         data-dev-historycurve="@Resources.devHistoryMode">

    </div> 
    
</article >
@section MapModeScripts{
    <script src="http://webapi.amap.com/maps?v=1.3&key=20bfaeaa29dde4edc6b521bdb13252f0"></script>
    <script src="http://api.map.baidu.com/api?v=2.0&ak=j8HK07y0Sc6V3n9UMLo1Wd5IYFCBMEyU"></script>
    <script src="~/assets/js/maplibrarybaidu.js"></script>    
}